
        <div data-role="footer" data-position="fixed" data-tap-toggle="false">
            <div data-role="navbar">
                <ul>
                    <li><a href="recommendsMobile" data-icon="" data-ajax="false"><small>Picks</small></a></li>
                    <li><a href="ratingsMobile" data-icon="" data-ajax="false"><small>Ratings</small></a></li>
                    <li><a href="wishlistMobile" data-icon=""data-ajax="false"><small>WishList</small></a></li>
                    <li><a href="searchMobile" data-icon="" data-ajax="false"><small>Search</small></a></li>
                    <li><a href="userMobile" data-icon="" data-ajax="false"><small>Account</small></a></li>
                </ul>
            </div><!-- /navbar -->                             
        </div><!-- /footer -->